In [124]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [125]:
dataset = pd.read_excel('Ruchi 150.xlsx', sheet_name = 'Satisfaction')

In [126]:
dataset.head()

Gender      Age Education  S.1  S.2  S.3  S.4  S.5  S.6  S.7  \
0    Male  Group 2    Degree    1    1    1    1    1    1    2   
1  Female  Group 3      Ph.D    1    2    2    2    2    1    4   
2    Male  Group 2        PG    1    1    1    1    1    1    1   
3    Male  Group 1  UGC-NET9    2    1    2    2    2    2    3   
4    Male  Group 3      Ph.D    1    1    1    1    2    3    2   

        ...        S.26  S.27  S.28  S.29  S.30  S.31  S.32  Tot Points  \
0       ...           1     2     1     2     1     1     1          54   
1       ...           2     4     1     3     2     2     2          74   
2       ...           1     2     1     2     1     1     1          51   
3       ...           2     3     3     3     2     2     3          91   
4       ...           2     4     1     1     1     1     1          59   

             Flag         Formula  
0  Strongly Agree  Strongly Agree  
1           Agree           Agree  
2  Strongly Agree  Strongly Agree  
3       Can't Say       Can't Say  
4  Strongly Agree           Agree  

[5 rows x 38 columns]

In [127]:
dataset = dataset.iloc[:, [3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34]]

In [128]:
dataset.head()

S.1  S.2  S.3  S.4  S.5  S.6  S.7  S.8  S.9  S.10  ...   S.23  S.24  S.25  \
0    1    1    1    1    1    1    2    5    2     3  ...      2     2     2   
1    1    2    2    2    2    1    4    4    2     2  ...      1     2     4   
2    1    1    1    1    1    1    1    3    2     3  ...      3     2     2   
3    2    1    2    2    2    2    3    3    3     3  ...      3     2     4   
4    1    1    1    1    2    3    2    2    2     1  ...      2     2     2   

   S.26  S.27  S.28  S.29  S.30  S.31  S.32  
0     1     2     1     2     1     1     1  
1     2     4     1     3     2     2     2  
2     1     2     1     2     1     1     1  
3     2     3     3     3     2     2     3  
4     2     4     1     1     1     1     1  

[5 rows x 32 columns]

In [129]:
statements = []

In [130]:
dataset.shape[1]

32

In [131]:
for j in range(dataset.shape[1]):
    statements.append([sum([1 for i in range(len(dataset)) if dataset.iloc[i, j] == 1]),
                       sum([1 for i in range(len(dataset)) if dataset.iloc[i, j] == 2]),
                       sum([1 for i in range(len(dataset)) if dataset.iloc[i, j] == 3]),
                       sum([1 for i in range(len(dataset)) if dataset.iloc[i, j] == 4]),
                       sum([1 for i in range(len(dataset)) if dataset.iloc[i, j] == 5])])

In [132]:
statements

[[63, 78, 4, 3, 2],
 [64, 73, 9, 2, 2],
 [46, 87, 10, 5, 2],
 [56, 66, 20, 6, 2],
 [25, 55, 55, 13, 2],
 [23, 50, 66, 9, 2],
 [13, 49, 66, 6, 16],
 [12, 30, 83, 16, 9],
 [23, 80, 31, 11, 5],
 [16, 65, 44, 19, 6],
 [21, 83, 30, 12, 4],
 [23, 54, 40, 21, 12],
 [62, 70, 15, 2, 1],
 [47, 73, 12, 15, 3],
 [24, 75, 29, 19, 3],
 [25, 57, 42, 24, 2],
 [18, 62, 46, 22, 2],
 [31, 63, 23, 25, 8],
 [34, 73, 22, 12, 9],
 [33, 40, 23, 23, 31],
 [10, 27, 45, 29, 39],
 [6, 15, 42, 47, 40],
 [24, 58, 50, 8, 10],
 [44, 70, 15, 7, 14],
 [9, 78, 29, 16, 18],
 [29, 73, 15, 20, 13],
 [13, 59, 27, 34, 17],
 [47, 88, 10, 4, 1],
 [20, 87, 30, 13, 0],
 [48, 69, 18, 13, 2],
 [58, 60, 21, 11, 0],
 [34, 86, 15, 12, 3]]

In [121]:
dataset.iloc[:, 7].values

array([5, 4, 0, 3, 2, 3, 3, 2, 3, 3, 2, 3, 3, 2, 3, 3, 1, 3, 3, 4, 3, 3,
       3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 2, 2, 2, 4, 3, 3, 2, 2, 3, 3,
       5, 3, 3, 5, 2, 3, 4, 4, 5, 3, 4, 5, 3, 3, 4, 2, 2, 2, 2, 1, 2, 2,
       1, 3, 4, 2, 3, 3, 5, 4, 3, 3, 4, 3, 3, 1, 3, 3, 2, 3, 3, 3, 5, 2,
       1, 3, 2, 3, 3, 1, 3, 4, 3, 3, 3, 3, 3, 3, 2, 1, 2, 2, 1, 3, 4, 2,
       3, 2, 2, 3, 3, 3, 3, 5, 4, 3, 3, 1, 3, 3, 4, 3, 3, 3, 3, 1, 3, 3,
       3, 3, 5, 2, 4, 2, 3, 2, 2, 3, 3, 1, 3, 3, 4, 3, 3, 3])

In [122]:
dataset.iloc[:, 15].values

array([2, 1, 0, 1, 3, 2, 3, 2, 2, 3, 2, 1, 2, 2, 3, 3, 2, 2, 3, 2, 3, 3,
       3, 3, 3, 2, 1, 3, 1, 2, 4, 2, 4, 1, 3, 3, 3, 2, 3, 4, 2, 2, 3, 4,
       2, 4, 3, 2, 2, 3, 2, 2, 3, 2, 4, 2, 1, 2, 4, 2, 2, 2, 1, 1, 2, 1,
       1, 3, 4, 2, 4, 1, 1, 2, 4, 4, 2, 3, 4, 1, 5, 1, 1, 2, 4, 4, 2, 2,
       2, 5, 3, 2, 3, 1, 3, 2, 3, 3, 3, 3, 3, 3, 1, 1, 2, 1, 1, 3, 4, 2,
       4, 2, 2, 3, 4, 4, 1, 1, 2, 4, 4, 2, 2, 3, 2, 3, 2, 1, 3, 1, 2, 2,
       4, 4, 2, 2, 4, 2, 4, 2, 2, 3, 3, 2, 2, 3, 2, 3, 3, 3])

In [123]:
dataset.iloc[:, 23].values

array([2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 2, 2, 3, 4, 2, 5, 1, 2, 5, 2,
       2, 1, 1, 2, 2, 1, 3, 5, 1, 1, 1, 3, 2, 2, 2, 3, 3, 1, 2, 2, 1, 2,
       3, 2, 4, 2, 3, 3, 4, 4, 2, 2, 2, 2, 3, 2, 2, 1, 5, 5, 1, 2, 2, 1,
       2, 2, 2, 1, 1, 1, 5, 2, 1, 1, 3, 3, 1, 2, 2, 1, 2, 1, 2, 4, 2, 1,
       2, 3, 2, 3, 2, 5, 1, 2, 5, 2, 2, 1, 1, 1, 1, 2, 2, 1, 2, 2, 2, 1,
       1, 2, 2, 1, 2, 1, 1, 5, 2, 1, 1, 2, 5, 1, 2, 5, 2, 2, 1, 3, 5, 1,
       2, 4, 2, 1, 2, 1, 1, 2, 2, 3, 4, 2, 5, 1, 2, 5, 2, 2])